# golangci-lint configuration
# See: https://golangci-lint.run/usage/configuration/
version: "2"

run:
  timeout: 5m
  go: "1.24"

linters:
  enable:
    - errcheck
    - gosimple
    - govet
    - ineffassign
    - staticcheck
    - unused
    - goimports
    - goconst
    - gocyclo
    - gosec
    - misspell
    - unconvert
    - unparam
    - whitespace
    - gofumpt

issues:
  max-issues-per-linter: 0
  max-same-issues: 0
