apiVersion: v1
kind: ServiceAccount
metadata:
  name: alert-reaction-operator
  namespace: default
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: alert-reaction-operator
rules:
- apiGroups:
  - alertreaction.io
  resources:
  - alertreactions
  verbs:
  - get
  - list
  - watch
  - create
  - update
  - patch
  - delete
- apiGroups:
  - alertreaction.io
  resources:
  - alertreactions/status
  verbs:
  - get
  - update
  - patch
- apiGroups:
  - alertreaction.io
  resources:
  - alertreactions/finalizers
  verbs:
  - update
- apiGroups:
  - batch
  resources:
  - jobs
  verbs:
  - get
  - list
  - watch
  - create
  - update
  - patch
  - delete
- apiGroups:
  - ""
  resources:
  - configmaps
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - ""
  resources:
  - secrets
  verbs:
  - get
  - list
  - watch
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: alert-reaction-operator
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: alert-reaction-operator
subjects:
- kind: ServiceAccount
  name: alert-reaction-operator
  namespace: default
