{{- if .Values.rbac.create -}}
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "alert-reaction-operator.fullname" . }}
  labels:
    {{- include "alert-reaction-operator.labels" . | nindent 4 }}
  {{- with include "alert-reaction-operator.annotations" . }}
  annotations:
    {{- . | nindent 4 }}
  {{- end }}
rules:
# AlertReaction resources
- apiGroups:
  - alertreaction.io
  resources:
  - alertreactions
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - alertreaction.io
  resources:
  - alertreactions/finalizers
  verbs:
  - update
- apiGroups:
  - alertreaction.io
  resources:
  - alertreactions/status
  verbs:
  - get
  - patch
  - update
# Jobs
- apiGroups:
  - batch
  resources:
  - jobs
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
# Core resources
- apiGroups:
  - ""
  resources:
  - configmaps
  - secrets
  verbs:
  - get
  - list
  - watch
# Leader election
- apiGroups:
  - ""
  resources:
  - configmaps
  verbs:
  - get
  - list
  - watch
  - create
  - update
  - patch
  - delete
- apiGroups:
  - coordination.k8s.io
  resources:
  - leases
  verbs:
  - get
  - list
  - watch
  - create
  - update
  - patch
  - delete
# Events for debugging
- apiGroups:
  - ""
  resources:
  - events
  verbs:
  - create
  - patch
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ include "alert-reaction-operator.fullname" . }}
  labels:
    {{- include "alert-reaction-operator.labels" . | nindent 4 }}
  {{- with include "alert-reaction-operator.annotations" . }}
  annotations:
    {{- . | nindent 4 }}
  {{- end }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ include "alert-reaction-operator.fullname" . }}
subjects:
- kind: ServiceAccount
  name: {{ include "alert-reaction-operator.serviceAccountName" . }}
  namespace: {{ .Release.Namespace }}
{{- end }}
